# Generated by Django 2.1.6 on 2019-03-03 06:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publish_date',
            field=models.DateField(default=datetime.datetime(2019, 3, 3, 6, 43, 7, 962945, tzinfo=utc), verbose_name='published_date'),
        ),
    ]
